### ISSUE TITLE
Javadocky presents empty dropdown if no other repositories with the same group id have been previously loaded

### ISSUE THREAD

**Issue by solonovamax** [KengoTODA/javadocky#288]
Reproducing:
 Note: Before performing this, make sure to **remove all cached artifacts and pages** (`rm -rf ~/.javadocky)

1. Load the javadocky url `/doc/ca.solo-studios/slf4k`
2. Open "slf4k" dropdown.
3. Dropdown is empty.
![image](https://user-images.githubusercontent.com/46940694/153691068-4cdaa8cd-971b-4912-b632-44d3f412ac7a.png)
4. Load javadocky url `/doc/ca.solo-studios/strata`.
5. Press "strata" dropdown.
6. slf4k and strata options are now shown.
![image](https://user-images.githubusercontent.com/46940694/153691170-38856042-b056-498f-8f31-521df8935c29.png)

Expected:
There should either be
1. No dropdown
2. A dropdown with a single element (namely, the current artifact)
3. No menu

Or else, it is confusing to any users who see an empty dropdown.

**Comment by KengoTODA** [comment]
Open a PR instead.

**Comment by solonovamax** [comment]
I would be happy to open a PR, but as said in all of my previous comments, this is an issue that should be used for tracking the fix, as well as discussion of other things related to the issue.
