### ISSUE TITLE
Javadocky does not include artifact in dropdown on first load of the page

### ISSUE THREAD

**Issue by solonovamax** [KengoTODA/javadocky#289]
Reproducing:
Note: Before performing this, make sure to **remove all cached artifacts and pages** (`rm -rf ~/.javadocky`)
1. Load javadocky url `/doc/ca.solo-studios/slf4k`.
2. Load javadocky url `/doc/ca.solo-studios/strata`.
3. Open "strata" dropdown.
4. The dropdown contains 1 item, when it should contain 2.
![image](https://user-images.githubusercontent.com/46940694/153691333-9f5a3aca-7fd5-426d-9402-3c17a2983fd6.png)
5. Select the "slf4k" item.
6. Return to the strata page.
7. Open the "strata" dropdown.
8. The dropdown now contains 2 items.
![image](https://user-images.githubusercontent.com/46940694/153691379-402e60db-93d8-4432-8ecb-7ae602e5cf85.png)

Expected:
The results should always be consistent as to whether it shows 1 item or 2.

Related to #288.

**Comment by KengoTODA** [comment]
Open a PR instead.

**Comment by solonovamax** [comment]
I would be happy to open a PR, but as said in all of my previous comments, this is an issue that should be used for tracking the fix, as well as discussion of other things related to the issue.
