### ISSUE TITLE
If embedded iframe page exceeds the length of the screen, then two scroll bars are rendered

### ISSUE THREAD

**Issue by solonovamax** [KengoTODA/javadocky#290]
Reproducing:
1. Navigate to javadocky url `/doc/ca.solo-studios/slf4k/`.
2. Expand the `org.slf4j.kotlin` package on the left of the screen.
3. Select the `KLogger` element.
4. Open the "Functions" tab
5. On the right hand side of the screen, two scroll bars are rendered.
   The first scroll bar is for the main page, and the second is for the embeded iframe.
   The main page should not have a scroll bar, as the iframe should be appropriately resized to fit the page.
![image](https://user-images.githubusercontent.com/46940694/153691646-3fb2d15e-fb4e-4ae4-8da5-5a46c5dcba46.png)

**Comment by KengoTODA** [comment]
Open a PR instead.
