### ISSUE TITLE
Javadocky does not rewrite URL when navigating javadoc

### ISSUE THREAD

**Issue by solonovamax** [KengoTODA/javadocky#291]
Current behaviour:
When navigating to a URL, you cannot link users to a specific javadoc page.
This includes a specific version of the javadoc.

Expected behaviour:
It should be possible to link to a specific javadoc page, say, `/doc/ca.solo-studios/slf4k/latest/-s-l-f4-k/org.slf4j.kotlin/-k-logger/index.html` ([Preview on javadoc.io](https://javadoc.io/doc/ca.solo-studios/strata/latest/ca/solostudios/strata/package-summary.html))
Or a specific version of the javadoc. ([Preview on javadoc.io](https://javadoc.io/doc/ca.solo-studios/strata/1.0.0/index.html))

Reproducing:
1. Navigate to `/doc/ca.solo-studios/strata`
2. Select the `ca.solostudios.strata` package.
3. URL should be rewritten to `/doc/ca.solo-studios/strata/1.1.1/ca/solostudios/strata/package-summary.html`, or preferably, `/doc/ca.solo-studios/strata/1.1.1/ca/solostudios/strata/package-summary` (with `.html` removed)
Further, the version is not included in the URL, which means users cannot be linked to a specific javadoc version via a URL.

**Comment by KengoTODA** [comment]
Open a PR instead.

**Comment by solonovamax** [comment]
I would be happy to open a PR for this, although I am not familiar with this particular component of spring boot, nor the required js to modify the page url.

The issue exists for the purpose of tracking the progress of the feature before it is added, as well as discussion about the feature itself and any alternatives/things that could be added on.
