### ISSUE TITLE
Badge generator is not complete

### ISSUE THREAD

**Issue by solonovamax** [KengoTODA/javadocky#293]
The [badge generator](https://github.com/KengoTODA/javadocky/blob/master/src/main/resources/static/index.html#L53-L57) is not complete.

Since there is no existing tracking issue for it, I am opening this issue for tracking purposes.

Related to #292.

**Comment by KengoTODA** [comment]
Open a PR instead.

**Comment by solonovamax** [comment]
Why has this issue been closed?

The point of this issue is to exist for tracking the progress of the badge generator, as well as for others to comment on things they might like to see added to it.

I am more than happy to contribute to this through a PR, but there should also be an issue for it.
