### ISSUE TITLE
Various UI changes

### ISSUE THREAD

**Issue by solonovamax** [KengoTODA/javadocky#294]
This issue is for an assortment of UI changes.
Since most of them are minor changes, I am grouping them all into a signle issue.

### Navigation bar changes
Here is the current navigation bar for javadocky:
![image](https://user-images.githubusercontent.com/46940694/153692646-f67ff164-446a-4a4a-9fa6-d49da18217a2.png)
Here is the current navigation bar from https://javadoc.io for reference: 
![image](https://user-images.githubusercontent.com/46940694/153692605-6d7eeec1-adeb-47bb-a886-1b38d5fc629e.png)

#### Left align group and artifact
In javadoc.io, the artifact and group name are left aligned.
I would like if it was left-aligned for javadocky as well. But, it should at least be configurable.

#### Add home button
javadoc.io presents a button that returns you to the home page (https://javadoc.io/). The same should be presented for javadocky.

This currently exists in the form of the text "Javadocky", but it may be more intuitive to present a dedicated home button.

#### Present a button to download javadoc
javadoc.io has a button that allows you to download the javadoc jar.
It also shows a [popover](https://getbootstrap.com/docs/5.1/components/popovers/) that indicates the jar can be extracted.
![image](https://user-images.githubusercontent.com/46940694/153692779-4861d119-5063-4247-b368-c3ff798d054d.png)

#### Add a button to create links to the page
This feature depends on #292.
On javadoc.io, the "bookmark" button can be selected to generate links to pages:
![image](https://user-images.githubusercontent.com/46940694/153692829-f9a08907-ac8b-463b-adb3-3b00d0ba738e.png)

It presents the following [modal](https://getbootstrap.com/docs/5.1/components/modal/) when clicked: 
![image](https://user-images.githubusercontent.com/46940694/153692855-1c4921b7-f252-4224-bb2d-5aea70908327.png)

### Changes to homepage

For reference, here is the current javadocky home page:
![image](https://user-images.githubusercontent.com/46940694/153693006-0ac0d402-4fde-4dc7-8c22-6acc7c8683fe.png)

And here is the javadoc.io home page:
![image](https://user-images.githubusercontent.com/46940694/153693024-a36af6a3-bd5c-4ab7-83fc-39e9a1ee847c.png)

#### Allow users to add a custom icon
A nice feature would be to allow users to add a custom icon for the homepage.

I'm not sure how easy/difficult this would be using spring boot, as I do not have experience with it, but ideally, javadocky would first attempt to resolve the icon relative to the run dir, and if it cannot find it, it falls back to one located in the resources.

#### Allow users to specify custom text for the homepage
Currently, the "This is a clone of [javadoc.io](https://javadoc.io/), based on Spring Boot v2.5.2 and Spring WebFlux v5.3.8. Visit [GitHub](https://github.com/KengoTODA/javadocky) to fork!" text is hardcoded into javadocky.

It would be nice if this was configurable via a config file (perhaps, YAML?) of some sort.

Since this is currently using a templating engine, it should not be too hard to do.

#### Allow users to submit maven artifact coordinates and be directed to the appropriate url
It would be nice for there to be two methods of specifying coordinates:
1. Group Id + Artifact Id
   
    This is how javadoc.io currently functions.
   ![image](https://user-images.githubusercontent.com/46940694/153693219-0637a048-5f2c-4f3a-987f-cd93b53b26e2.png)
2. Gradle library coordinates
   This would allow users to enter in coordinates in the form `group:artifact:version` and it would direct them to the appropriate page.

**Comment by KengoTODA** [comment]
This repo is not open for any suggestions.

**Comment by solonovamax** [comment]
Why is the repo not open to suggestions?

I would be more than happy to implement some of them myself, so long as they are within the real of my knowledge.

Is there a reason you are not open to suggestions?
