### ISSUE TITLE
Ability to specify multiple javadoc sources

### ISSUE THREAD

**Issue by solonovamax** [KengoTODA/javadocky#295]
Currently, only a single source can be specified via `javadocky.maven.repository`.

It would be nice to allow for multiple sources, allowing you to specify your own personal maven repo, in addition to the central repo.

**Comment by KengoTODA** [comment]
Open a PR instead.

**Comment by solonovamax** [comment]
Hello,
I am more than happy to open a PR for this instead, but there should be an issue that exists for tracking purposes as well as discussion about alternatives/etc.
